package src.statuses;

public enum RegisterStatus {
    SUCCESS,
    EMPTY_USERNAME_AND_PASSWORD_AND_EMAIL,
    EMPTY_USERNAME_AND_PASSWORD,
    EMPTY_USERNAME_AND_EMAIL,
    EMPTY_PASSWORD_AND_EMAIL,
    EMPTY_USERNAME,
    EMPTY_PASSWORD,
    EMPTY_EMAIL,
    USERNAME_TAKEN,
    INVALID_PASSWORD
}
